### ISSUE TITLE
Seems like display range is not applied when expression is applied

### ISSUE THREAD

**Issue by ilyaly** [hongfaqiu/TIFFImageryProvider#10]
I'm rendering an NDVI index map from multiband geotiff using `single` mode with `expression` and `domain` parameters configured and everything works perfect. 

However when I add `displayRange` configuration (with `applyDisplayRange = true` of course) it does not effects visualization at all.  The value of `domain` parameter in my case is equal to `[0, 1]` and the value of `displayRange` parameter is equal to `[0.5, 0.8]`

Am I doing something wrong or `expression` is not compatible with `displayRange`?

Thanks in advance.

**Comment by hongfaqiu** [comment]
Sorry, I have been busy with other things lately. This bug has already been fixed. Please try again.
