### ISSUE TITLE
当resx和resy不相等时，加载后图片显示发虚，同时发现resampleMethod参数是无效的

### ISSUE THREAD

**Issue by xmsuperman** [hongfaqiu/TIFFImageryProvider#18]
pixel size 为 5，2.5
效果如下图所示

![cesium-error](https://github.com/hongfaqiu/TIFFImageryProvider/assets/32294479/05fe9a4c-d652-4220-a512-427d0480088f)
错误的

=========================================

![ol-correct](https://github.com/hongfaqiu/TIFFImageryProvider/assets/32294479/7e3c2b71-0090-41c0-8ce0-5194921be724)
正确的

另外
TIFFImageryProvider的resampleMethod参数目前是无效的，按显示效果来看默认为linear
期望效果如正确的ol图片所示，当设置成nearest时显示的是预期的效果

在@2.7.0版本重现

**Comment by hongfaqiu** [comment]
@xmsuperman 已修复，请查看 #30
