### ISSUE TITLE
"No data" areas show as solid black instead of transparent when using convertToRGB true or multi-band

### ISSUE THREAD

**Issue by hillmb79** [hongfaqiu/TIFFImageryProvider#19]
Great library!  Struggling on one issue, I have a number of multi-band RGB TIFFs I'm trying to render but I can't seem to find a way to get the "empty" no data area to just be transparent so that the background shows through.  Instead, it is always solid black - presumably because the RGB value across the bands is 0 / 0 / 0.

As an example, here's what I see using TIFFImageryProvider in Cesium:
![image](https://github.com/hongfaqiu/TIFFImageryProvider/assets/26581644/27ec1c18-21f5-41c7-805e-d6bc81ef41f6)

Here is what I see for the same image using QGIS which is setup by default to use "No Color" for the no data values, so these no data areas just display the layer beneath rather than solid black:
![image](https://github.com/hongfaqiu/TIFFImageryProvider/assets/26581644/519d3544-0888-4466-bf34-9c06603c7391)

If I change the QGIS No Data color to black, I get a result that looks like the TIFFImageryProvider in Cesium which is what makes me think TIFFImageryProvider must be using rgb(0,0,0) for the no data color:

![image](https://github.com/hongfaqiu/TIFFImageryProvider/assets/26581644/cf8c765f-e5d0-4896-b9e6-47d2027bf1cd)

Any help greatly appreciated!  Thank you.

**Comment by hongfaqiu** [comment]
Done! You can now customize RGB colors using the colorMapping parameter in renderOptions. The default scheme is to only make black transparent.

**Comment by hillmb79** [comment]
Just some feedback - this is working great now and I'm able to get the map looking the way I need to.  Thanks for the quick update!

**Comment by hongfaqiu** [comment]
Thank you for your feedback. I'm glad to be able to assist you.
