### ISSUE TITLE
Inverted colors when rendering RGB Raster

### ISSUE THREAD

**Issue by ilyaly** [hongfaqiu/TIFFImageryProvider#2]
Example of [RGB raster](https://oin-hotosm.s3.amazonaws.com/56f9b5a963ebf4bc00074e70/0/56f9c2d42b67227a79b4faec.tif) rendering in [COG Explorer](https://geotiffjs.github.io/cog-explorer/#long=168.457&lat=-17.553&zoom=17&scene=https://oin-hotosm.s3.amazonaws.com/56f9b5a963ebf4bc00074e70/0/56f9c2d42b67227a79b4faec.tif&bands=&pipeline=):

![image](https://user-images.githubusercontent.com/30498863/233334316-db86df6d-c300-4a81-82ca-4afbb44423c5.png)

Example of rendering with default parameters via TIFFImageryProvider:

![image](https://user-images.githubusercontent.com/30498863/233338227-d2f0313b-e13f-402d-ba62-67fea9f856c6.png)

P.S. Setting Chrome to 3.0 makes the look better, but still far from true colors.

**Comment by hongfaqiu** [comment]
Thank you for your issue, I'll fix it in this week.

**Comment by hongfaqiu** [comment]
Fixed yet in v2.2.0, now add multi band tiff will first try rgb mode.

**Comment by hongfaqiu** [comment]
There are still black areas present currently. If it's necessary to remove these black areas, I will add an optional exclusion parameter.

**Comment by ilyaly** [comment]
Thank you! 

You are really doing a great job that is very valuable for the community. As Cesium is moving very slow in everything excepting 3D Tiles you are the hero we need!

**Comment by hongfaqiu** [comment]
Thank you for your kind words. I have only done some insignificant work with the strong support of Cesium, and I hope that it can be helpful to everyone.
