### ISSUE TITLE
npm安装tiff-imagery-provider 时候  报错

### ISSUE THREAD

**Issue by 13333141732** [hongfaqiu/TIFFImageryProvider#23]
Module parse failed: Unexpected token (1157:8)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| }`;
| class plot {
>   canvas;
|   currentDataset;
|   datasetCollection;

**Comment by mqYYYY** [comment]
请问您这个问题解决了吗？我也遇到了这个这个报错
