### ISSUE TITLE
Order cannot be adjusted with other providers.

### ISSUE THREAD

**Issue by kwunjaehyun** [hongfaqiu/TIFFImageryProvider#26]
Thank you for providing a great library.

There is one problem: the order cannot be adjusted with other layers. It is always displayed at the top. Is it possible to solve it?

**Comment by hongfaqiu** [comment]
TIFFImageryProvider is just a provider. Have you constructed the corresponding ImageryLayer?
I haven't encountered any issues with adjusting the level of ImageryLayer in my project. Could you provide an online demo for debugging purposes?
Here is my demo: https://stackblitz.com/edit/vitejs-vite-jeczao?file=src%2Findex.ts
![image](https://github.com/hongfaqiu/TIFFImageryProvider/assets/62411296/e77103e3-ee73-4545-add5-514ee9a2a746)
