### ISSUE TITLE
经过测试，在2.1.1版本DEMO，3 band RBG byte Eight bit unsigned integer 无法正确渲染显示

### ISSUE THREAD

**Issue by xmsuperman** [hongfaqiu/TIFFImageryProvider#3]
<a href="https://oin-hotosm.s3.amazonaws.com/56f9b5a963ebf4bc00074e70/0/56f9c2d42b67227a79b4faec.tif">example url</a>

**Comment by hongfaqiu** [comment]
正要尝试解决这个bug

**Comment by xmsuperman** [comment]
现在demo的默认样式添加进tif数据源是无效的，无论单通还是多通都是无法正确显示的

**Comment by hongfaqiu** [comment]
已发现这个问题，下次提交一起解决了

**Comment by xmsuperman** [comment]
作者辛苦

**Comment by hongfaqiu** [comment]
v2.2.0已修复，添加了convertToRGB配置，默认加载时，多波段tif将优先尝试rgb模式加载，demo中添加了相关示例
![image](https://user-images.githubusercontent.com/62411296/233612024-88401c49-b71f-49d6-882d-c3bb3e4dd496.png)

**Comment by xmsuperman** [comment]
![20230421185248](https://user-images.githubusercontent.com/32294479/233618598-149d732a-550b-48e3-84c2-a0a9e69a4bfd.png)
刚测试，2.20版本demo在增加单波段数据时报错。

**Comment by hongfaqiu** [comment]
抱歉，是我的代码有误，forEach中的异步方法没有做await处理，已修复
