### ISSUE TITLE
No colors in Firefox with v2.11.0

### ISSUE THREAD

**Issue by TheMrCam** [hongfaqiu/TIFFImageryProvider#31]
# Overview

Upon updating to `tiff-imagery-provider@2.11.0`, I noticed Firefox would not render the imagery with color, no matter what I tried for `renderOptions.single`.

Screenshot:
<img width="80%" alt="Screenshot 2024-07-09 at 13 34 49" src="https://github.com/hongfaqiu/TIFFImageryProvider/assets/63317483/6f9f04a7-c513-404b-ab6b-30c74fc310dd">

I checked Microsoft Edge and had no issues with the color.

I noticed a new warning in the Firefox console:
```txt
WebGL warning: texImage: Requested size at this level is unsupported.
```

Upon further investigation, it appears the problem lies in Firefox's WebGL implementation, with a "Max Texture Size" of 8192 (half that of Safari or Microsoft Edge, as confirmed via [WebGL Report](https://webglreport.com/?v=2)).

## The fix(?)

I was able to find a workaround by changing the width value `10 ** 4` to `8192` at [plotty/index.ts#L132](https://github.com/hongfaqiu/TIFFImageryProvider/blob/e2a563eb77af0385b0690bf5f6b939e20ef64cdc/packages/TIFFImageryProvider/src/plotty/index.ts#L132).

I can provide a PR with that one-liner if desired, but I haven't extensively checked to confirm that change doesn't cause side effects--so I wanted to bring it to your attention first, in case you have a better idea/more robust solution.

# Thanks!

This is a great package, keep fighting the good fight.

**Comment by hongfaqiu** [comment]
@TheMrCam Thank you for your discovery! If possible, please submit a pull request, and I will quickly release a new corrected version.
