### ISSUE TITLE
在高纬度地区展示效果异常

### ISSUE THREAD

**Issue by lxzylllsl** [hongfaqiu/TIFFImageryProvider#33]
您好，我使用这个插件展示全球的数据时，默认的展示效果在高纬度地区存在异常， 当缩放到某一level时，部分瓦片又能正常显示。

![WX20240715-175742](https://github.com/user-attachments/assets/8ada6ea7-73d7-46c8-b240-f7ee3da6f0ed)
![WX20240715-175756](https://github.com/user-attachments/assets/c4a0320d-874d-4227-a813-ce795323bf28)

**Comment by lxzylllsl** [comment]
我尝试了   这样的方式设置地形数据，能够部分解决问题，但是在高纬度还是存在异常
const terrainLayer = await Cesium.CesiumTerrainProvider.fromIonAssetId(1);

    this.cesiumViewer = new Cesium.Viewer(cesiumContainer, {
      terrainProvider: terrainLayer
    });

![WX20240715-231256@2x](https://github.com/user-attachments/assets/ac49e2e2-b50a-4f00-b401-7fbc6d7b132e)

**Comment by hongfaqiu** [comment]
@lxzylllsl 能否提供出现异常的文件？

**Comment by lxzylllsl** [comment]
[global.tiff.zip](https://github.com/user-attachments/files/16242469/global.tiff.zip)
这是我使用的文件

**Comment by hongfaqiu** [comment]
@lxzylllsl 我在demo中打开的效果是正常的，使用的cesium版本是1.119.0
![QQ_1721099779169](https://github.com/user-attachments/assets/09597802-d6f4-4d7c-b1e7-2ae8c71184ff)
![QQ_1721099824007](https://github.com/user-attachments/assets/b66e7da8-0e06-47ee-900a-61f3e3254311)

**Comment by lxzylllsl** [comment]
升级了cesium之后问题解决，谢谢您！
