### ISSUE TITLE
经测试，v2.3.0版本的demo，加载多通道 Multi band还会报异常啊

### ISSUE THREAD

**Issue by xmsuperman** [hongfaqiu/TIFFImageryProvider#8]
![20230423-mband](https://user-images.githubusercontent.com/32294479/233815225-222fa649-247a-48c2-81bc-a96ab5502174.png)

如下图所示

**Comment by hongfaqiu** [comment]
该问题已修复，原因是geotiff的worker解码池初始化失败，因为cog不太依赖解码性能，所以代码修改为如果初始化失败，就使用主线程了
